app/routes.py
"""
This module defines the routing and view logic for the Flask application. It handles
requests, processes them, and returns appropriate responses, rendering HTML templates
or redirecting to other endpoints as needed.
"""

import datetime
from flask import render_template, request, redirect, url_for, session, Blueprint
from .utils import (
    send_mail,
    generate_ai_workout,
    get_number_of_workouts,
    get_number_of_exercises,
    get_workout_from_db,
    get_workout_id,
    get_workout_by_id,
)

main = Blueprint('main', __name__)


@main.route('/', methods=['GET', 'POST'])
def index():
    """
      Renders the main page and handles form submissions for user messages.
      Sends an email with user message if the request method is POST.
      Also fetches counts for exercises and workouts to display on the main page.
    """
    if request.method == 'POST':
        name = request.form['name']
        email = request.form['email']
        phone = request.form['phone']
        message = request.form['Message']
        send_mail(name, email, phone, message)

    year = datetime.date.today().year
    exercises_count = get_number_of_exercises()
    workouts_count = get_number_of_workouts()
    print(workouts_count)

    return render_template('index.html', year=year, exercises_count=exercises_count, workouts_count=workouts_count)


@main.route('/workout')
def workout():
    """Renders the workout page."""
    return render_template('workout.html')


@main.route('/workout/run', methods=['GET', 'POST'])
def run():
    """Renders the run workout page and handles the user's workout details"""
    if request.method == 'POST':
        duration = request.form['workout-duration']
        level = request.form['fitness-level']
        running_type = request.form['running-type']
        print(duration, level, running_type)
        return redirect(
            url_for('main.get_run_workouts', duration=duration, fitness_level=level, running_type=running_type))

    return render_template('run.html')


@main.route('/workout/strength', methods=['GET', 'POST'])
def strength():
    """Renders the strength workout page and handles the user's workout details"""
    if request.method == 'POST':
        duration = request.form['workout-duration']
        level = request.form['fitness-level']
        goal = request.form['fitness-goal']
        equipment = request.form['equipment-access']
        print(duration, level, goal, equipment)
        return redirect(url_for('main.get_strength_workouts', duration=duration, fitness_level=level, fitness_goal=goal,
                                equipment_access=equipment))

    return render_template('strength.html')


@main.route('/strength_workouts')
def get_strength_workouts():
    """Retrieves and displays strength workouts based on user-provided criteria"""
    workout_type = "strength"
    duration = request.args.get('duration')
    fitness_level = request.args.get('fitness_level')
    fitness_goal = request.args.get('fitness_goal')
    equipment_access = request.args.get('equipment_access')

    workouts = get_workout_from_db(workout_type=workout_type, duration=duration, fitness_level=fitness_level,
                                   fitness_goal=fitness_goal, equipment_access=equipment_access)

    if len(workouts) != 0:
        workout_id = get_workout_id(workouts)
        return redirect(url_for('main.display_workout', workout_id=workout_id))

    return redirect(
        url_for('main.ai_workout', duration=duration, fitness_level=fitness_level, fitness_goal=fitness_goal,
                equipment_access=equipment_access))


@main.route('/run_workouts')
def get_run_workouts():
    """Retrieves and displays run workouts based on user-provided criteria"""
    workout_type = "run"
    duration = request.args.get('duration')
    fitness_level = request.args.get('fitness_level')
    running_type = request.args.get('running_type')

    print("run workouts: ", workout_type, duration, fitness_level, running_type)

    workouts = get_workout_from_db(workout_type=workout_type, duration=duration,
                                   fitness_level=fitness_level, running_type=running_type)

    if len(workouts) != 0:
        workout_id = get_workout_id(workouts)
        return redirect(url_for('main.display_workout', workout_id=workout_id))

    return redirect(
        url_for('main.ai_workout', duration=duration, fitness_level=fitness_level, running_type=running_type))


@main.route('/display-workout/<int:workout_id>')
def display_workout(workout_id):
    """Displays details of a specific workout."""
    workout_details = get_workout_by_id(workout_id)

    workout_name = workout_details[0].workout_name

    return render_template('workouts.html', workout_name=workout_name, exercises=workout_details)


@main.route('/get_ai_workouts', methods=['GET', 'POST'])
def ai_workout():
    """Fetch workout details and generates a workout based on user-provided criteria via AI"""
    if request.method == 'POST':
        duration = request.form.get('duration')
        fitness_level = request.form.get('fitness_level')
        fitness_goal = request.form.get('fitness_goal')
        equipment_access = request.form.get('equipment_access')
        running_type = request.form.get('running_type')

    else:
        duration = request.args.get('duration')
        fitness_level = request.args.get('fitness_level')
        fitness_goal = request.args.get('fitness_goal')
        equipment_access = request.args.get('equipment_access')
        running_type = request.args.get('running_type')

    if request.method == 'POST':
        workout_output = generate_ai_workout(duration, fitness_level, fitness_goal, equipment_access, running_type)

        try:
            session['workout_name'] = workout_output["workout_name"]
            session['workout_details'] = workout_output["workout_details"]
            return redirect(url_for('main.display_ai_workout'))

        except ValueError as e:
            print("Error parsing the output:", e)

    return render_template('no-workouts.html')


@main.route('/display-ai-workout')
def display_ai_workout():
    """Displays details of a specific AI workout."""
    workout_name = session.get('workout_name', 'Default Workout')
    workout_details_tuples = session.get('workout_details', [])
    workout_details = [
        {
            'exercise_name': detail[0],
            'exercise_description': detail[1] if len(detail) > 1 else 'No description',
            'sets': detail[2] if len(detail) > 2 else 'No sets info',
            'repetitions': detail[3] if len(detail) > 3 else 'No repetitions info',
            'rest_time': detail[4] if len(detail) > 4 else 'No rest time info'
        }
        for detail in workout_details_tuples
    ]

    return render_template('workouts.html', workout_name=workout_name, exercises=workout_details)


@main.errorhandler(404)
def page_not_found(_):
    """Renders a custom 404 error page."""
    error_code = 404
    error_message = "We can't find the page you're looking for."
    return render_template('error.html', error_code=error_code, error_message=error_message), 404


@main.errorhandler(500)
def service_unavailable(_):
    """Renders a custom 500 error page."""
    error_code = 500
    error_message = "Internal Server error - It's not you, it's us"
    return render_template('error.html', error_code=error_code, error_message=error_message), 500

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>FLEX</title>
    <link rel="stylesheet" type="text/css" href="../static/css/core.css"/>
    <link rel="stylesheet" type="text/css" href="../static/css/styles.css"/>
    <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/css?family=Roboto&display=swap"

    />

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bungee+Spice&display=swap" rel="stylesheet">
</head>
<body>
<div class="bg"></div>

<!-- ============================================ -->
<!--                    Section 1                 -->
<!-- ============================================ -->

<section id="hero-82">
    <div class="cs-container">
        <h1 class="cs-title">FLEX</h1>
        <p class="cs-text">
    With more than <span class="text">{{ workouts_count }}+</span> workouts and over <span class="text">{{ exercises_count }}+</span> unique exercises,
    Flex will help you create your ideal workout routine.
    Simply input your workout preferences,
    and we'll handle the rest. So, what are you waiting for?
</p>
        <a href="{{ url_for('main.workout') }}" class="cs-button-solid">Start Now</a>
    </div>

    <!-- Background Image -->
    <picture class="cs-background">
        <source media="(max-width: 600px)" srcset="../static/images/gym.jpg"/>
        <source media="(min-width: 601px)" srcset="../static/images/gym.jpg"/>
        <img
                loading="lazy"
                decoding="async"
                src="../static/images/gym.jpg"
                alt="kitchen"
                width="2250"
                height="1500"
                aria-hidden="true"
        />
    </picture>
</section>

<!-- ============================================ -->
<!--                   Section 2                  -->
<!-- ============================================ -->

<section id="steps-889">
    <div class="cs-container">
        <div class="cs-content">
            <span class="cs-topper">Our Process</span>
            <h2 class="cs-title">How It Works</h2>
        </div>
        <ul class="cs-card-group">
            <li class="cs-item">
                <picture class="cs-picture">
                    <img
                            class="cs-icon"
                            src="../static/svg/footprint.svg"
                            alt="icon"
                            width="32"
                            height="32"
                            loading="lazy"
                            decoding="async"
                            aria-hidden="true"
                    />
                </picture>
                <h3 class="cs-h3">Step 1: Start Your Fitness Adventure!</h3>
                <p class="cs-item-p">
                    Tell us a bit about yourself, and we'll tailor a workout that
                    perfectly fits you.
                </p>
            </li>
            <!--Arrow-->
            <li class="cs-item cs-arrow" aria-hidden="true">
                <img
                        class="cs-arrow-img"
                        src="https://csimg.nyc3.cdn.digitaloceanspaces.com/Icons%2Farrow-curve-right.svg"
                        alt="icon"
                        width="80"
                        height="76"
                        loading="lazy"
                        decoding="async"
                        aria-hidden="true"
                />
            </li>
            <li class="cs-item">
                <picture class="cs-picture">
                    <img
                            class="cs-icon"
                            src="../static/svg/robot.svg"
                            alt="icon"
                            width="32"
                            height="32"
                            loading="lazy"
                            decoding="async"
                            aria-hidden="true"
                    />
                </picture>
                <h3 class="cs-h3">Step 2: Your Customized Workout Awaits</h3>
                <p class="cs-item-p">
                    Our algorithm crafts a unique workout based on your details.
                </p>
            </li>
            <!--Arrow-->
            <li class="cs-item cs-arrow" aria-hidden="true">
                <img
                        class="cs-arrow-img"
                        src="https://csimg.nyc3.cdn.digitaloceanspaces.com/Icons%2Farrow-curve-right.svg"
                        alt="icon"
                        width="80"
                        height="76"
                        loading="lazy"
                        decoding="async"
                        aria-hidden="true"
                />
            </li>
            <li class="cs-item">
                <picture class="cs-picture">
                    <img
                            class="cs-icon"
                            src="../static/svg/fitnees.svg"
                            alt="icon"
                            width="32"
                            height="32"
                            loading="lazy"
                            decoding="async"
                            aria-hidden="true"
                    />
                </picture>
                <h3 class="cs-h3">Step 3: Time to move, Dive into the Fun!</h3>
                <p class="cs-item-p">
                    Lace up, hit play, and enjoy a workout personalized to meet your
                    goals.
                </p>
            </li>
        </ul>
    </div>
</section>

<!-- ============================================ -->
<!--                   Contact                    -->
<!-- ============================================ -->

<section id="contact-718">
    <div class="cs-container">
        <picture class="cs-picture">
            <source
                    media="(max-width: 600px)"
                    srcset="../static/images/running.jpg"
            />
            <source
                    media="(min-width: 601px)"
                    srcset="../static/images/running.jpg"
            />
            <img
                    decoding="async"
                    src="../static/images/running.jpg"
                    alt="runner"
                    width="610"
                    height="425"
                    aria-hidden="true"
            />
        </picture>
        <div class="cs-content">
            <span class="cs-topper">Contact Us</span>
            <h2 class="cs-title">Get in Touch</h2>
            <p class="cs-text">
                Have questions, feedback, or just want to chat about your fitness
                journey? We're here for you! Our dedicated team is ready to assist
                you. Whether you need assistance with our app, have suggestions for
                improvement, or simply want to share your success stories, don't
                hesitate to reach out.
            </p>
            <!--Form-->
            <form
                    class="cs-form"
                    id="cs-form-718"
                    name="Contact Form"
                    method="POST"
                    action="{{ url_for('main.index') }}"
            >
                <label class="cs-label">
                    Name
                    <input
                            class="cs-input"
                            required
                            type="text"
                            id="name-718"
                            name="name"
                            placeholder="Name"
                    />
                </label>
                <label class="cs-label cs-email">
                    Email
                    <input
                            class="cs-input"
                            required
                            type="text"
                            id="email-718"
                            name="email"
                            placeholder="Email"
                    />
                </label>
                <label class="cs-label cs-phone">
                    Phone
                    <input
                            class="cs-input"
                            required
                            type="text"
                            id="phone-718"
                            name="phone"
                            placeholder="Phone"
                    />
                </label>
                <label class="cs-label">
                    Message
                    <textarea
                            class="cs-input cs-textarea"
                            required
                            name="Message"
                            id="message-718"
                            placeholder="Write message..."
                    ></textarea>
                </label>
                <button class="cs-button-solid cs-submit" type="submit">
                    Send
                </button>
            </form>
        </div>
    </div>
</section>

<!-- ============================================ -->
<!--                   Footer                     -->
<!-- ============================================ -->

<footer id="cs-footer-107">
    <div class="cs-container">
        <ul class="cs-ul">
            <li> This is a test/li>
            <!-- <li>This is a test</li> -->
            <li>© {{year}} Flex Inc</li>
            <li>Welcome to my personal project! Please note that this site is a creative and experimental space for me to explore and develop my skills. It is not intended to be a professional or commercially useful platform. Enjoy browsing, and thank you for your understanding and support!</li>
        </ul>
    </div>
</footer>

<!-- ============================================ -->
<!--      Popup For sending contact message       -->
<!-- ============================================ -->
<div id="myModal" class="modal">
    <div class="modal-content">
        <span class="close">&times;</span>
        <p id="modalText">Some text in the Modal..</p>
    </div>
</div>

<script>

var modal = document.getElementById("myModal");
var span = document.getElementsByClassName("close")[0];


span.onclick = function() {
  modal.style.display = "none";
}


function showModal(message) {
  document.getElementById("modalText").innerHTML = message;
  modal.style.display = "block";
}


window.onclick = function(event) {
  if (event.target == modal) {
    modal.style.display = "none";
  }
}

</script>

{% with messages = get_flashed_messages() %}
{% if messages %}
<script type="text/javascript">
      window.onload = function() {
        showModal("{{ messages[0] }}");
      };

</script>
{% endif %}
{% endwith %}


</body>
</html>

app/templates/run.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>FLEX</title>
    <link rel="stylesheet" type="text/css" href="../static/css/core.css"/>
    <link rel="stylesheet" type="text/css" href="../static/css/styles.css"/>
    <link rel="stylesheet" type="text/css" href="../static/css/styles2.css"/>
    <link
            rel="stylesheet"
            type="text/css"
            href="../static/css/styles-workout.css"
    />
    <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/css?family=Roboto&display=swap"
    />
</head>
<body>
<div class="bg"></div>

<!-- ============================================ -->
<!--                   Gallery                    -->
<!-- ============================================ -->

<section id="gallery-1446">
    <div class="cs-container">
        <div class="cs-content">
            <div class="cs-flex">
                <span class="cs-topper">Step 2</span>
                <h2 class="cs-title">
                    Tell us about yourself to create your workout.
                </h2>
                <a
                        href="{{ url_for('main.workout') }}"
                        class="cs-button-6"
                        aria-label="read more about us"
                >
                    Go Back
                    <!--SVG Arrow-->
                    <div class="cs-wrapper">
                        <svg
                                class="cs-icon"
                                aria-hidden="true"
                                width="24"
                                height="24"
                                viewBox="0 0 24 24"
                                fill="none"
                                xmlns="http://www.w3.org/2000/svg"
                        >
                            <path
                                    d="M17.92 11.62C17.8724 11.4973 17.801 11.3851 17.71 11.29L12.71 6.29C12.6168 6.19676 12.5061 6.1228 12.3842 6.07234C12.2624 6.02188 12.1319 5.99591 12 5.99591C11.7337 5.99591 11.4783 6.1017 11.29 6.29C11.1968 6.38324 11.1228 6.49393 11.0723 6.61575C11.0219 6.73758 10.9959 6.86814 10.9959 7C10.9959 7.2663 11.1017 7.5217 11.29 7.71L14.59 11H7C6.73478 11 6.48043 11.1054 6.29289 11.2929C6.10536 11.4804 6 11.7348 6 12C6 12.2652 6.10536 12.5196 6.29289 12.7071C6.48043 12.8946 6.73478 13 7 13H14.59L11.29 16.29C11.1963 16.383 11.1219 16.4936 11.0711 16.6154C11.0203 16.7373 10.9942 16.868 10.9942 17C10.9942 17.132 11.0203 17.2627 11.0711 17.3846C11.1219 17.5064 11.1963 17.617 11.29 17.71C11.383 17.8037 11.4936 17.8781 11.6154 17.9289C11.7373 17.9797 11.868 18.0058 12 18.0058C12.132 18.0058 12.2627 17.9797 12.3846 17.9289C12.5064 17.8781 12.617 17.8037 12.71 17.71L17.71 12.71C17.801 12.6149 17.8724 12.5028 17.92 12.38C18.02 12.1365 18.02 11.8635 17.92 11.62Z"
                                    fill="#1a1a1a"
                            />
                        </svg>
                    </div>
                </a>
            </div>
            <form
                    method="POST"
                    action="{{ url_for('main.run') }}"
            >
                <div class="signup-container">
                    <div class="right-container">
                        <header>
                            <div class="multi-select">
                                <label for="duration-0-30">Workout Duration</label>
                                <div class="radio-container">
                                    <input
                                            id="duration-0-30"
                                            name="workout-duration"
                                            type="radio"
                                            value="0-30"
                                            checked
                                    />
                                    <label for="duration-0-30">0-30 mins</label>
                                    <input
                                            id="duration-30-60"
                                            name="workout-duration"
                                            type="radio"
                                            value="30-60"
                                    />
                                    <label for="duration-30-60">30-60 mins</label>
                                    <input
                                            id="duration-60-plus"
                                            name="workout-duration"
                                            type="radio"
                                            value="60+"
                                    />
                                    <label for="duration-60-plus">60+ mins</label>
                                </div>
                            </div>

                            <div class="multi-select">
                                <label for="beginner">Fitness Level</label>
                                <div class="radio-container">
                                    <input
                                            id="beginner"
                                            name="fitness-level"
                                            type="radio"
                                            value="beginner"
                                            checked
                                    />
                                    <label for="beginner">Beginner</label>
                                    <input
                                            id="intermediate"
                                            name="fitness-level"
                                            type="radio"
                                            value="intermediate"
                                    />
                                    <label for="intermediate">Intermediate</label>
                                    <input
                                            id="advanced"
                                            name="fitness-level"
                                            type="radio"
                                            value="advanced"
                                    />
                                    <label for="advanced">Advanced</label>
                                </div>
                            </div>

                            <div class="multi-select">
                                <label for="long-run">Running Type</label>
                                <div class="radio-container">
                                    <input
                                            id="long-run"
                                            name="running-type"
                                            type="radio"
                                            value="long-run"
                                            checked
                                    />
                                    <label for="long-run">Long Run</label>
                                    <input
                                            id="hiit"
                                            name="running-type"
                                            type="radio"
                                            value="hiit"
                                    />
                                    <label for="hiit">HIIT</label>
                                    <input
                                            id="recovery"
                                            name="running-type"
                                            type="radio"
                                            value="recovery"
                                    />
                                    <label for="recovery">Recovery</label>
                                    <input
                                            id="fartlek"
                                            name="running-type"
                                            type="radio"
                                            value="fartlek"
                                    />
                                    <label for="fartlek">Fartlek</label>
                                </div>
                            </div>
                        </header>
                        <footer>
                            <button class="cs-button-5" type="submit">
                                <span class="cs-button-text">Get your workout!</span>
                            </button>
                        </footer>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>
</body>
</html>

app/templates/workout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>FLEX</title>
    <link rel="stylesheet" type="text/css" href="../static/css/core.css" />
    <link rel="stylesheet" type="text/css" href="../static/css/styles.css" />
    <link rel="stylesheet" type="text/css" href="../static/css/styles2.css" />
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Roboto&display=swap"
    />
  </head>
  <body>
    <div class="bg"></div>

    <!-- ============================================ -->
    <!--                   Gallery                    -->
    <!-- ============================================ -->

    <section id="gallery-1446">
      <div class="cs-container">
        <div class="cs-content">
          <div class="cs-flex">
            <span class="cs-topper">Step 1</span>
            <h2 class="cs-title">Choose Your Workout</h2>
            <a
              href="{{ url_for('main.index') }}"
              class="cs-button-6"
              aria-label="read more about us"
            >
              Go Back
              <!--SVG Arrow-->
              <div class="cs-wrapper">
                <svg
                  class="cs-icon"
                  aria-hidden="true"
                  width="24"
                  height="24"
                  viewBox="0 0 24 24"
                  fill="none"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    d="M17.92 11.62C17.8724 11.4973 17.801 11.3851 17.71 11.29L12.71 6.29C12.6168 6.19676 12.5061 6.1228 12.3842 6.07234C12.2624 6.02188 12.1319 5.99591 12 5.99591C11.7337 5.99591 11.4783 6.1017 11.29 6.29C11.1968 6.38324 11.1228 6.49393 11.0723 6.61575C11.0219 6.73758 10.9959 6.86814 10.9959 7C10.9959 7.2663 11.1017 7.5217 11.29 7.71L14.59 11H7C6.73478 11 6.48043 11.1054 6.29289 11.2929C6.10536 11.4804 6 11.7348 6 12C6 12.2652 6.10536 12.5196 6.29289 12.7071C6.48043 12.8946 6.73478 13 7 13H14.59L11.29 16.29C11.1963 16.383 11.1219 16.4936 11.0711 16.6154C11.0203 16.7373 10.9942 16.868 10.9942 17C10.9942 17.132 11.0203 17.2627 11.0711 17.3846C11.1219 17.5064 11.1963 17.617 11.29 17.71C11.383 17.8037 11.4936 17.8781 11.6154 17.9289C11.7373 17.9797 11.868 18.0058 12 18.0058C12.132 18.0058 12.2627 17.9797 12.3846 17.9289C12.5064 17.8781 12.617 17.8037 12.71 17.71L17.71 12.71C17.801 12.6149 17.8724 12.5028 17.92 12.38C18.02 12.1365 18.02 11.8635 17.92 11.62Z"
                    fill="#1a1a1a"
                  />
                </svg>
              </div>
            </a>
          </div>
        </div>
        <!--Gallery-->
        <div class="cs-gallery">
          <!--Picture 1-->
          <a href="{{ url_for('main.run') }}">
            <picture class="cs-image">
              <source
                media="(max-width: 600px)"
                srcset="../static/images/running-man.jpg"
              />
              <source
                media="(min-width: 601px)"
                srcset="../static/images/running-man.jpg"
              />
              <img
                loading="lazy"
                decoding="async"
                src="../static/images/running-man.jpg"
                alt="gallery"
                width="305"
                height="400"
              />
            </picture>
          </a>
          <!--Picture 2-->
          <a href="{{ url_for('main.strength') }}">
            <picture class="cs-image">
              <source
                media="(max-width: 600px)"
                srcset="../static/images/lifting-man.png"
              />
              <source
                media="(min-width: 601px)"
                srcset="../static/images/lifting-man.png"
              />
              <img
                loading="lazy"
                decoding="async"
                src="../static/images/lifting-man.png"
                alt="gallery"
                width="305"
                height="400"
              />
            </picture>
          </a>
        </div>
      </div>
    </section>
  </body>
</html>